### ISSUE TITLE
[Feature Request]可以选择语言LOGO

### ISSUE THREAD

**Issue by HydrogenDeuterium** [mrcaidev/language-rating#1]
rt

**Comment by mrcaidev** [comment]
可以做到选择【常用语言】的 LOGO。

---

设计原型的时候，实际上是有意做成【输入框】而非【下拉选择】的。下面是我当时的一些考量：

1. 语言种类过多，不便设计 UI。
    - 把[所有语言](https://en.wikipedia.org/wiki/List_of_programming_languages)全塞到下拉框里，显然是不现实的。比方说我如果喜欢 TypeScript 或者 Zig，那我可能要翻半天才能找到自己想要的语言，还不如自己直接输入；
    - 当然，也可以做成【常用语言下拉框】+【小语种搜索框】的形式，但个人认为引入了太多 DX 上的复杂度，而 UX 上带来的体验却并没有很大的提升——点击单元格-点击搜索框-输入语言-找到 LOGO-确认，这一套流程，真的要比直接输入的用户体验要好吗？我个人认为提升不大。
2. 引入图片带来的额外开销。
    - LOGO 需要开发者提供。这意味着开发者需要手动找数十种语言的 LOGO，然后放到现在的 `src/data/questions.json` 里。这个事情一开始我还真干了，挺麻烦……如果有类似于 `https://programming-logo.com/cpp.svg` 这样的网站 / API 的话，事情的确会简单一点，但是这就意味着用户访问网站的时候，网站还要向 API 发出数十个请求来下载这些 LOGO——在 LOGO 和性能之间，我是宁愿选择后者的。
    - 就像刚刚说的，就算在本地 host 图片，对网站的性能仍然有额外开销。
3. 实际上，每个人并不是把每个单元格都严格地填上某一种语言的。大家可能会加定语修饰（例：某一版本的某一语言），可能会自由发挥写一些短句（所有 XXX 的语言）。这是我在构建原型时，最终决定不采用 LOGO 的原因；而我所看到的反馈也的确如此。

所以，综上所述，我个人仍认为【文本输入】是最佳的选择。但如果有更多人都觉得【选择 LOGO】是更好的方式，那我肯定会加上这个 Feature 的。

**Comment by xxr0ss** [comment]
全都要，既能文字，又能LOGO就好了
